---
- hosts: all
  become: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
- hosts: BuildServers
  become: yes
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day
  - name: "Install Java"
    apt:
      name: openjdk-8-jdk
      state: present
  - name: "Install Jenkins on Node1"
    apt_key: url=https://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
  - name: ensure the repository is configured
    apt_repository: repo='deb https://pkg.jenkins.io/debian-stable binary/' state=present
  - name: "Check Jenkins is installed"
    apt: name=jenkins update_cache=yes
    become: yes
  - name: "Start the Jenkins service"
    service: name=jenkins state=started
  - name: "Pause for 10 seconds"
    pause:
        seconds: 10
  - name: "Get Jenkins initial Admin Password"
    shell: "cat /var/lib/jenkins/secrets/initialAdminPassword"
- hosts: DockerServers
  become: yes
  tasks:
  - name: "Download the Docker script"
    get_url:
      url: https://raw.githubusercontent.com/devopsbc01/Scripts/master/dockerubuntu.sh
      dest: /dockerubuntu.sh
      mode: '7777'
  - name: "Execute the Docker script"
    shell: yes | /dockerubuntu.sh
  - name: "Pause for 10 seconds"
    pause:
      seconds: 10
  - name: "Modify the ansadmin user group"
    shell: sudo usermod -a -G docker ansadmin
    changed_when: false
    register: result
  - name: "Echo the password"
    debug:
     var: result.stdout
  - name: "Pause for 10 seconds"
    pause:
      seconds: 10
- hosts: DBServers
  become: yes
  tasks:
  - name: "Download the Postgres script"
    get_url:
      url: https://raw.githubusercontent.com/devopsbc01/Scripts/master/Postgresql-Install-1.sh
      dest: /Postgresql-Install-1.sh
      mode: '7777'
  - name: "Execute the Postgres script"
    shell: yes | /Postgresql-Install-1.sh
