---
- hosts: localhost
  become: true
  tasks:
  - name: create docker image using war file
    command: docker build -t prod-simple-devops-image:latest .
    args:
      chdir: /home/ansadmin/Devops_case_study/prod

  - name: create tag to image
    command: docker tag prod-simple-devops-image sathishsekhar/prod-simple-devops-image

  - name: Log into DockerHub
    docker_login:
      username: xxxxxx
      password: xxxxxx
      email: sathishkumaran85@gmail.com

  - name: push image on to dockerhub
    command: docker push sathishsekhar/prod-simple-devops-image

  - name: remove docker immages from ansible server
    command: docker rmi prod-simple-devops-image:latest sathishsekhar/prod-simple-devops-image
    ignore_errors: yes
