---
- hosts: ProdServers
  become: true
  tasks:
  - name: stop if we have old docker container
    command: docker stop prod-simple-devops-container
    ignore_errors: yes

  - name: remove stopped docker container
    command: docker rm prod-simple-devops-container
    ignore_errors: yes

  - name: remove current docker image
    command: docker rmi sri40718/prod-simple-devops-image
    ignore_errors: yes
#    register: result
#    failed_when:
#      - result.rc == 0
#      - '"docker" not in result.stdout'


  - name: pull docker image from dockerhub
    command: docker pull sri40718/prod-simple-devops-image:latest

  - name: creating docker image
    command: docker run -d --name prod-simple-devops-container -p 8080:8080 sri40718/prod-simple-devops-image:latest
